### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by thomasleveil** [mrenoe/BT-Listener#1]
Hi, 

Would you mind sharing how to managed to build the .exe file with pyinstaller?
I'm stuck with `ImportError: No module named bluetooth`

regards

**Comment by mrenoe** [comment]
Have you downloaded PyBluez? That's the module named Bluetooth. Ensure that is being correctly ported in and i'll take a further look this evening.

**Comment by thomasleveil** [comment]
I did but still having the error. Did you install pybluez with pip?

**Comment by mrenoe** [comment]
So, i started tonight from a fresh build on a fresh PC and realized there were more dependencies here than i expected. In addition to the ones on my readme, setuptools was needed also. 

I'm on windows 10, using 32 bit Python 2.7. Pybluez requires 32 bit i believe. I didn't get anything through pip, it was all zip files and setup.py. Once i had everything installed it was as simple as "$PyInstaller --onefile Slidesurf.py" 

I downloaded PyBluez from "https://pypi.python.org/pypi/PyBluez" and used the 2.7 executable. 

is the 'bluetooth' folder within your "Lib\site-packages" directory?

**Comment by thomasleveil** [comment]
Thank you for the suggestions. Unfortunately I'm still having issue. However switching to [bbfreeze](https://pypi.python.org/pypi/bbfreeze/) solves the issue.
